<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Zapatilla Addict De Pu Mujer 47 Street__2c91a9</name>
   <tag></tag>
   <elementGuidId>a66b50bf-f6f5-40d1-8cc8-25d3fd90244a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='root-app']/div/div[5]/section/section/div[2]/div/div/div/div[2]/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1c0eb975-36fb-44b9-bdba-e1005ce27438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>db8d3148-e905-4281-a2ba-d6ca631f2e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://http2.mlstatic.com/D_Q_NP_738156-MLA49581086064_042022-P.webp</value>
      <webElementGuid>ed0256bc-a49c-4ad2-adcd-b786183d197f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamic-carousel__img</value>
      <webElementGuid>2dcecb6f-0395-4f6a-bc98-f52219fdd1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Campera Mujer Boucle Courtney System </value>
      <webElementGuid>ab11f30c-8b6e-458d-9ff1-774952c5dc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://http2.mlstatic.com/D_Q_NP_738156-MLA49581086064_042022-P.webp 1x,
      https://http2.mlstatic.com/D_Q_NP_2X_738156-MLA49581086064_042022-P.webp 2x,</value>
      <webElementGuid>e557d21f-73ff-4057-adfe-bb8b20cd833f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root-app&quot;)/div[@class=&quot;light hub&quot;]/div[5]/section[@class=&quot;dynamic__carousel&quot;]/section[@class=&quot;dynamic-carousel-normal-desktop&quot;]/div[@class=&quot;carousel-container&quot;]/div[@class=&quot;slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[@class=&quot;andes-card andes-card--flat andes-card--default andes-card--padding-default&quot;]/div[@class=&quot;dynamic-carousel__item-container&quot;]/a[1]/div[@class=&quot;dynamic-carousel__link-container&quot;]/img[@class=&quot;dynamic-carousel__img&quot;]</value>
      <webElementGuid>f552ff46-bcb0-44db-b672-0aa6fe5671c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='root-app']/div/div[5]/section/section/div[2]/div/div/div/div[2]/div/div/a/div/img</value>
      <webElementGuid>1ada2fc5-a651-4e7c-9641-7f486506d7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Campera Mujer Boucle Courtney System ']</value>
      <webElementGuid>1dbd1559-350b-4b09-b84c-066056f2974f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/div/img</value>
      <webElementGuid>693826e3-00e0-4c64-bef8-6cfa90ca9e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://http2.mlstatic.com/D_Q_NP_738156-MLA49581086064_042022-P.webp' and @alt = 'Campera Mujer Boucle Courtney System ']</value>
      <webElementGuid>7f38a178-3482-4b98-be66-c97b4f5041aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
