<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Zapatilla Addict De Pu Mujer 47 Street__2c91a9</name>
   <tag></tag>
   <elementGuidId>a66b50bf-f6f5-40d1-8cc8-25d3fd90244a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='root-app']/div/div[5]/section/section/div[2]/div/div/div/div[2]/div/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f870779b-dffd-43a2-bebb-68bf7309af92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>11326370-0885-47da-b0a0-28af7033f0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://http2.mlstatic.com/D_Q_NP_738156-MLA49581086064_042022-P.webp</value>
      <webElementGuid>b448358b-e77d-44fb-a0bb-c3d7574f90fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamic-carousel__img</value>
      <webElementGuid>fc224c64-9c0b-4515-8b5b-5cc70464cdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Campera Mujer Boucle Courtney System </value>
      <webElementGuid>f0d7fa53-b8bc-425e-b802-96df34776212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://http2.mlstatic.com/D_Q_NP_738156-MLA49581086064_042022-P.webp 1x,
      https://http2.mlstatic.com/D_Q_NP_2X_738156-MLA49581086064_042022-P.webp 2x,</value>
      <webElementGuid>2b2ecc8a-9b78-4fa3-ad12-5e97408b8130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root-app&quot;)/div[@class=&quot;light hub&quot;]/div[5]/section[@class=&quot;dynamic__carousel&quot;]/section[@class=&quot;dynamic-carousel-normal-desktop&quot;]/div[@class=&quot;carousel-container&quot;]/div[@class=&quot;slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[@class=&quot;andes-card andes-card--flat andes-card--default andes-card--padding-default&quot;]/div[@class=&quot;dynamic-carousel__item-container&quot;]/a[1]/div[@class=&quot;dynamic-carousel__link-container&quot;]/img[@class=&quot;dynamic-carousel__img&quot;]</value>
      <webElementGuid>aae544dd-48ba-4553-832f-361149756ec4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='root-app']/div/div[5]/section/section/div[2]/div/div/div/div[2]/div/div/a/div/img</value>
      <webElementGuid>18dc2da2-8a9a-444e-9c13-954b2fe7cbc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Campera Mujer Boucle Courtney System ']</value>
      <webElementGuid>9d5be79f-8176-449c-ab40-1444c5e7bc52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/div/img</value>
      <webElementGuid>74207b68-d06a-428a-ae12-bcfa9ac233d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://http2.mlstatic.com/D_Q_NP_738156-MLA49581086064_042022-P.webp' and @alt = 'Campera Mujer Boucle Courtney System ']</value>
      <webElementGuid>ecedc971-d64b-4392-9607-f98a5a5b323d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
