<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Zapatilla Addict De Pu Mujer 47 Street__2c91a9</name>
   <tag></tag>
   <elementGuidId>a66b50bf-f6f5-40d1-8cc8-25d3fd90244a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root-app&quot;]/div/div[5]/section/section/div[2]/div/div/div/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fb131422-dfb0-48e8-a413-baecaacfb527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>96082312-220d-4f81-ab6d-a4931f05b366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://http2.mlstatic.com/D_Q_NP_738156-MLA49581086064_042022-P.webp</value>
      <webElementGuid>13f6e6a3-7ab1-48ff-a5f7-f1220dee351f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamic-carousel__img</value>
      <webElementGuid>a4f43451-488e-4ded-bf6f-0a177bf5bd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Campera Mujer Boucle Courtney System </value>
      <webElementGuid>240eb2c3-1ed6-40f7-af94-f2b2d861304e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://http2.mlstatic.com/D_Q_NP_738156-MLA49581086064_042022-P.webp 1x,
      https://http2.mlstatic.com/D_Q_NP_2X_738156-MLA49581086064_042022-P.webp 2x,</value>
      <webElementGuid>53840405-f38b-4b4c-a0d4-b7d469036e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root-app&quot;)/div[@class=&quot;light hub&quot;]/div[5]/section[@class=&quot;dynamic__carousel&quot;]/section[@class=&quot;dynamic-carousel-normal-desktop&quot;]/div[@class=&quot;carousel-container&quot;]/div[@class=&quot;slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[@class=&quot;andes-card andes-card--flat andes-card--default andes-card--padding-default&quot;]/div[@class=&quot;dynamic-carousel__item-container&quot;]/a[1]/div[@class=&quot;dynamic-carousel__link-container&quot;]/img[@class=&quot;dynamic-carousel__img&quot;]</value>
      <webElementGuid>45ecd5d2-5cd9-487e-b63b-d97789af1461</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='root-app']/div/div[5]/section/section/div[2]/div/div/div/div[2]/div/div/a/div/img</value>
      <webElementGuid>c9781e4d-35a3-457e-8637-5dff9b1ce911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Campera Mujer Boucle Courtney System ']</value>
      <webElementGuid>72aaa161-2307-4fe2-868c-8f92f425fde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/div/img</value>
      <webElementGuid>31d58ee6-6eef-4fe8-943f-6c01b302d59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://http2.mlstatic.com/D_Q_NP_738156-MLA49581086064_042022-P.webp' and @alt = 'Campera Mujer Boucle Courtney System ']</value>
      <webElementGuid>fddbe1b8-13fd-4205-b5d6-2cd5467bbd6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
