<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Moda</name>
   <tag></tag>
   <elementGuidId>06e9741a-5c3d-444b-8c43-75cb7189120f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Moda')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b272029c-a08f-47cf-928c-ccbf0016c1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mercadolibre.com.ar/c/ropa-y-accesorios#menu=categories</value>
      <webElementGuid>ac7dd04d-a019-4546-bd6b-6ba9027cfeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Moda</value>
      <webElementGuid>24215a6f-b437-42ff-8d1d-9c7164e29597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;nav-header nav-header-plus&quot;]/div[@class=&quot;nav-bounds nav-bounds-with-cart nav-bounds-with-cp&quot;]/div[@class=&quot;nav-menu&quot;]/ul[@class=&quot;nav-menu-list&quot;]/li[@class=&quot;nav-menu-item nav-menu-chevron-down&quot;]/div[@class=&quot;nav-categs&quot;]/ul[@class=&quot;nav-categs-departments&quot;]/li[@class=&quot;nav-categs-departments__list nav-categs-departments__list--static&quot;]/a[1]</value>
      <webElementGuid>5a066c87-c8f7-4461-8c6b-b09eb22ff918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Moda')]</value>
      <webElementGuid>a127924d-9a9f-46b7-a6e8-43d134703bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accesorios para Vehículos'])[1]/following::a[1]</value>
      <webElementGuid>0f0892ce-ed75-4f52-bbd4-2c69c05d0d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deportes y Fitness'])[1]/following::a[2]</value>
      <webElementGuid>1d1048e3-8235-4344-8d10-ee6a35c48829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Juegos y Juguetes'])[1]/preceding::a[1]</value>
      <webElementGuid>91fbd5b9-bf54-45f9-8f10-4dee1daf5972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bebés'])[1]/preceding::a[2]</value>
      <webElementGuid>2424f6ee-65a5-48c8-8ee4-17acd4a712c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mercadolibre.com.ar/c/ropa-y-accesorios#menu=categories')]</value>
      <webElementGuid>6c7172e9-25c1-4ef5-8a40-36c630aab97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>2f103520-37fd-4811-b956-8e8fd70e6b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mercadolibre.com.ar/c/ropa-y-accesorios#menu=categories' and (text() = 'Moda' or . = 'Moda')]</value>
      <webElementGuid>d268fe27-0f93-48de-a56a-e7a900b38e8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
